//
//  TBUnicode.h
//  TapKitDemo
//
//  Created by Kevin on 5/8/14.
//  Copyright (c) 2014 Telligenty. All rights reserved.
//

#import <Foundation/Foundation.h>

//0000..007F; Basic Latin
#define TB_UNICODE_BLOCK_BASIC_LATIN @"TB_UNICODE_BLOCK_BASIC_LATIN"

//0080..00FF; Latin-1 Supplement
#define TB_UNICODE_BLOCK_LATIN_1_SUPPLEMENT @"TB_UNICODE_BLOCK_LATIN_1_SUPPLEMENT"

//0100..017F; Latin Extended-A
#define TB_UNICODE_BLOCK_LATIN_EXTENDED_A @"TB_UNICODE_BLOCK_LATIN_EXTENDED_A"

//0180..024F; Latin Extended-B
#define TB_UNICODE_BLOCK_LATIN_EXTENDED_B @"TB_UNICODE_BLOCK_LATIN_EXTENDED_B"

//0250..02AF; IPA Extensions
#define TB_UNICODE_BLOCK_IPA_EXTENSIONS @"TB_UNICODE_BLOCK_IPA_EXTENSIONS"

//02B0..02FF; Spacing Modifier Letters
#define TB_UNICODE_BLOCK_SPACING_MODIFIER_LETTERS @"TB_UNICODE_BLOCK_SPACING_MODIFIER_LETTERS"

//0300..036F; Combining Diacritical Marks
#define TB_UNICODE_BLOCK_COMBINING_DIACRITICAL_MARKS @"TB_UNICODE_BLOCK_COMBINING_DIACRITICAL_MARKS"

//0370..03FF; Greek and Coptic
#define TB_UNICODE_BLOCK_GREEK_AND_COPTIC @"TB_UNICODE_BLOCK_GREEK_AND_COPTIC"

//0400..04FF; Cyrillic
#define TB_UNICODE_BLOCK_CYRILLIC @"TB_UNICODE_BLOCK_CYRILLIC"

//0500..052F; Cyrillic Supplement
#define TB_UNICODE_BLOCK_CYRILLIC_SUPPLEMENT @"TB_UNICODE_BLOCK_CYRILLIC_SUPPLEMENT"

//0530..058F; Armenian
#define TB_UNICODE_BLOCK_ARMENIAN @"TB_UNICODE_BLOCK_ARMENIAN"

//0590..05FF; Hebrew
#define TB_UNICODE_BLOCK_HEBREW @"TB_UNICODE_BLOCK_HEBREW"

//0600..06FF; Arabic
#define TB_UNICODE_BLOCK_ARABIC @"TB_UNICODE_BLOCK_ARABIC"

//0700..074F; Syriac
#define TB_UNICODE_BLOCK_SYRIAC @"TB_UNICODE_BLOCK_SYRIAC"

//0750..077F; Arabic Supplement
#define TB_UNICODE_BLOCK_ARABIC_SUPPLEMENT @"TB_UNICODE_BLOCK_ARABIC_SUPPLEMENT"

//0780..07BF; Thaana
#define TB_UNICODE_BLOCK_THAANA @"TB_UNICODE_BLOCK_THAANA"

//07C0..07FF; NKo
#define TB_UNICODE_BLOCK_NKO @"TB_UNICODE_BLOCK_NKO"

//0800..083F; Samaritan
#define TB_UNICODE_BLOCK_SAMARITAN @"TB_UNICODE_BLOCK_SAMARITAN"

//0840..085F; Mandaic
#define TB_UNICODE_BLOCK_MANDAIC @"TB_UNICODE_BLOCK_MANDAIC"

//08A0..08FF; Arabic Extended-A
#define TB_UNICODE_BLOCK_ARABIC_EXTENDED_A @"TB_UNICODE_BLOCK_ARABIC_EXTENDED_A"

//0900..097F; Devanagari
#define TB_UNICODE_BLOCK_DEVANAGARI @"TB_UNICODE_BLOCK_DEVANAGARI"

//0980..09FF; Bengali
#define TB_UNICODE_BLOCK_BENGALI @"TB_UNICODE_BLOCK_BENGALI"

//0A00..0A7F; Gurmukhi
#define TB_UNICODE_BLOCK_GURMUKHI @"TB_UNICODE_BLOCK_GURMUKHI"

//0A80..0AFF; Gujarati
#define TB_UNICODE_BLOCK_GUJARATI @"TB_UNICODE_BLOCK_GUJARATI"

//0B00..0B7F; Oriya
#define TB_UNICODE_BLOCK_ORIYA @"TB_UNICODE_BLOCK_ORIYA"

//0B80..0BFF; Tamil
#define TB_UNICODE_BLOCK_TAMIL @"TB_UNICODE_BLOCK_TAMIL"

//0C00..0C7F; Telugu
#define TB_UNICODE_BLOCK_TELUGU @"TB_UNICODE_BLOCK_TELUGU"

//0C80..0CFF; Kannada
#define TB_UNICODE_BLOCK_KANNADA @"TB_UNICODE_BLOCK_KANNADA"

//0D00..0D7F; Malayalam
#define TB_UNICODE_BLOCK_MALAYALAM @"TB_UNICODE_BLOCK_MALAYALAM"

//0D80..0DFF; Sinhala
#define TB_UNICODE_BLOCK_SINHALA @"TB_UNICODE_BLOCK_SINHALA"

//0E00..0E7F; Thai
#define TB_UNICODE_BLOCK_THAI @"TB_UNICODE_BLOCK_THAI"

//0E80..0EFF; Lao
#define TB_UNICODE_BLOCK_LAO @"TB_UNICODE_BLOCK_LAO"

//0F00..0FFF; Tibetan
#define TB_UNICODE_BLOCK_TIBETAN @"TB_UNICODE_BLOCK_TIBETAN"

//1000..109F; Myanmar
#define TB_UNICODE_BLOCK_MYANMAR @"TB_UNICODE_BLOCK_MYANMAR"

//10A0..10FF; Georgian
#define TB_UNICODE_BLOCK_GEORGIAN @"TB_UNICODE_BLOCK_GEORGIAN"

//1100..11FF; Hangul Jamo
#define TB_UNICODE_BLOCK_HANGUL_JAMO @"TB_UNICODE_BLOCK_HANGUL_JAMO"

//1200..137F; Ethiopic
#define TB_UNICODE_BLOCK_ETHIOPIC @"TB_UNICODE_BLOCK_ETHIOPIC"

//1380..139F; Ethiopic Supplement
#define TB_UNICODE_BLOCK_ETHIOPIC_SUPPLEMENT @"TB_UNICODE_BLOCK_ETHIOPIC_SUPPLEMENT"

//13A0..13FF; Cherokee
#define TB_UNICODE_BLOCK_CHEROKEE @"TB_UNICODE_BLOCK_CHEROKEE"

//1400..167F; Unified Canadian Aboriginal Syllabics
#define TB_UNICODE_BLOCK_UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS @"TB_UNICODE_BLOCK_UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS"

//1680..169F; Ogham
#define TB_UNICODE_BLOCK_OGHAM @"TB_UNICODE_BLOCK_OGHAM"

//16A0..16FF; Runic
#define TB_UNICODE_BLOCK_RUNIC @"TB_UNICODE_BLOCK_RUNIC"

//1700..171F; Tagalog
#define TB_UNICODE_BLOCK_TAGALOG @"TB_UNICODE_BLOCK_TAGALOG"

//1720..173F; Hanunoo
#define TB_UNICODE_BLOCK_HANUNOO @"TB_UNICODE_BLOCK_HANUNOO"

//1740..175F; Buhid
#define TB_UNICODE_BLOCK_BUHID @"TB_UNICODE_BLOCK_BUHID"

//1760..177F; Tagbanwa
#define TB_UNICODE_BLOCK_TAGBANWA @"TB_UNICODE_BLOCK_TAGBANWA"

//1780..17FF; Khmer
#define TB_UNICODE_BLOCK_KHMER @"TB_UNICODE_BLOCK_KHMER"

//1800..18AF; Mongolian
#define TB_UNICODE_BLOCK_MONGOLIAN @"TB_UNICODE_BLOCK_MONGOLIAN"

//18B0..18FF; Unified Canadian Aboriginal Syllabics Extended
#define TB_UNICODE_BLOCK_UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED @"TB_UNICODE_BLOCK_UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED"

//1900..194F; Limbu
#define TB_UNICODE_BLOCK_LIMBU @"TB_UNICODE_BLOCK_LIMBU"

//1950..197F; Tai Le
#define TB_UNICODE_BLOCK_TAI_LE @"TB_UNICODE_BLOCK_TAI_LE"

//1980..19DF; New Tai Lue
#define TB_UNICODE_BLOCK_NEW_TAI_LUE @"TB_UNICODE_BLOCK_NEW_TAI_LUE"

//19E0..19FF; Khmer Symbols
#define TB_UNICODE_BLOCK_KHMER_SYMBOLS @"TB_UNICODE_BLOCK_KHMER_SYMBOLS"

//1A00..1A1F; Buginese
#define TB_UNICODE_BLOCK_BUGINESE @"TB_UNICODE_BLOCK_BUGINESE"

//1A20..1AAF; Tai Tham
#define TB_UNICODE_BLOCK_TAI_THAM @"TB_UNICODE_BLOCK_TAI_THAM"

//1B00..1B7F; Balinese
#define TB_UNICODE_BLOCK_BALINESE @"TB_UNICODE_BLOCK_BALINESE"

//1B80..1BBF; Sundanese
#define TB_UNICODE_BLOCK_SUNDANESE @"TB_UNICODE_BLOCK_SUNDANESE"

//1BC0..1BFF; Batak
#define TB_UNICODE_BLOCK_BATAK @"TB_UNICODE_BLOCK_BATAK"

//1C00..1C4F; Lepcha
#define TB_UNICODE_BLOCK_LEPCHA @"TB_UNICODE_BLOCK_LEPCHA"

//1C50..1C7F; Ol Chiki
#define TB_UNICODE_BLOCK_OL_CHIKI @"TB_UNICODE_BLOCK_OL_CHIKI"

//1CC0..1CCF; Sundanese Supplement
#define TB_UNICODE_BLOCK_SUNDANESE_SUPPLEMENT @"TB_UNICODE_BLOCK_SUNDANESE_SUPPLEMENT"

//1CD0..1CFF; Vedic Extensions
#define TB_UNICODE_BLOCK_VEDIC_EXTENSIONS @"TB_UNICODE_BLOCK_VEDIC_EXTENSIONS"

//1D00..1D7F; Phonetic Extensions
#define TB_UNICODE_BLOCK_PHONETIC_EXTENSIONS @"TB_UNICODE_BLOCK_PHONETIC_EXTENSIONS"

//1D80..1DBF; Phonetic Extensions Supplement
#define TB_UNICODE_BLOCK_PHONETIC_EXTENSIONS_SUPPLEMENT @"TB_UNICODE_BLOCK_PHONETIC_EXTENSIONS_SUPPLEMENT"

//1DC0..1DFF; Combining Diacritical Marks Supplement
#define TB_UNICODE_BLOCK_COMBINING_DIACRITICAL_MARKS_SUPPLEMENT @"TB_UNICODE_BLOCK_COMBINING_DIACRITICAL_MARKS_SUPPLEMENT"

//1E00..1EFF; Latin Extended Additional
#define TB_UNICODE_BLOCK_LATIN_EXTENDED_ADDITIONAL @"TB_UNICODE_BLOCK_LATIN_EXTENDED_ADDITIONAL"

//1F00..1FFF; Greek Extended
#define TB_UNICODE_BLOCK_GREEK_EXTENDED @"TB_UNICODE_BLOCK_GREEK_EXTENDED"

//2000..206F; General Punctuation
#define TB_UNICODE_BLOCK_GENERAL_PUNCTUATION @"TB_UNICODE_BLOCK_GENERAL_PUNCTUATION"

//2070..209F; Superscripts and Subscripts
#define TB_UNICODE_BLOCK_SUPERSCRIPTS_AND_SUBSCRIPTS @"TB_UNICODE_BLOCK_SUPERSCRIPTS_AND_SUBSCRIPTS"

//20A0..20CF; Currency Symbols
#define TB_UNICODE_BLOCK_CURRENCY_SYMBOLS @"TB_UNICODE_BLOCK_CURRENCY_SYMBOLS"

//20D0..20FF; Combining Diacritical Marks for Symbols
#define TB_UNICODE_BLOCK_COMBINING_DIACRITICAL_MARKS_FOR_SYMBOLS @"TB_UNICODE_BLOCK_COMBINING_DIACRITICAL_MARKS_FOR_SYMBOLS"

//2100..214F; Letterlike Symbols
#define TB_UNICODE_BLOCK_LETTERLIKE_SYMBOLS @"TB_UNICODE_BLOCK_LETTERLIKE_SYMBOLS"

//2150..218F; Number Forms
#define TB_UNICODE_BLOCK_NUMBER_FORMS @"TB_UNICODE_BLOCK_NUMBER_FORMS"

//2190..21FF; Arrows
#define TB_UNICODE_BLOCK_ARROWS @"TB_UNICODE_BLOCK_ARROWS"

//2200..22FF; Mathematical Operators
#define TB_UNICODE_BLOCK_MATHEMATICAL_OPERATORS @"TB_UNICODE_BLOCK_MATHEMATICAL_OPERATORS"

//2300..23FF; Miscellaneous Technical
#define TB_UNICODE_BLOCK_MISCELLANEOUS_TECHNICAL @"TB_UNICODE_BLOCK_MISCELLANEOUS_TECHNICAL"

//2400..243F; Control Pictures
#define TB_UNICODE_BLOCK_CONTROL_PICTURES @"TB_UNICODE_BLOCK_CONTROL_PICTURES"

//2440..245F; Optical Character Recognition
#define TB_UNICODE_BLOCK_OPTICAL_CHARACTER_RECOGNITION @"TB_UNICODE_BLOCK_OPTICAL_CHARACTER_RECOGNITION"

//2460..24FF; Enclosed Alphanumerics
#define TB_UNICODE_BLOCK_ENCLOSED_ALPHANUMERICS @"TB_UNICODE_BLOCK_ENCLOSED_ALPHANUMERICS"

//2500..257F; Box Drawing
#define TB_UNICODE_BLOCK_BOX_DRAWING @"TB_UNICODE_BLOCK_BOX_DRAWING"

//2580..259F; Block Elements
#define TB_UNICODE_BLOCK_BLOCK_ELEMENTS @"TB_UNICODE_BLOCK_BLOCK_ELEMENTS"

//25A0..25FF; Geometric Shapes
#define TB_UNICODE_BLOCK_GEOMETRIC_SHAPES @"TB_UNICODE_BLOCK_GEOMETRIC_SHAPES"

//2600..26FF; Miscellaneous Symbols
#define TB_UNICODE_BLOCK_MISCELLANEOUS_SYMBOLS @"TB_UNICODE_BLOCK_MISCELLANEOUS_SYMBOLS"

//2700..27BF; Dingbats
#define TB_UNICODE_BLOCK_DINGBATS @"TB_UNICODE_BLOCK_DINGBATS"

//27C0..27EF; Miscellaneous Mathematical Symbols-A
#define TB_UNICODE_BLOCK_MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A @"TB_UNICODE_BLOCK_MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A"

//27F0..27FF; Supplemental Arrows-A
#define TB_UNICODE_BLOCK_SUPPLEMENTAL_ARROWS_A @"TB_UNICODE_BLOCK_SUPPLEMENTAL_ARROWS_A"

//2800..28FF; Braille Patterns
#define TB_UNICODE_BLOCK_BRAILLE_PATTERNS @"TB_UNICODE_BLOCK_BRAILLE_PATTERNS"

//2900..297F; Supplemental Arrows-B
#define TB_UNICODE_BLOCK_SUPPLEMENTAL_ARROWS_B @"TB_UNICODE_BLOCK_SUPPLEMENTAL_ARROWS_B"

//2980..29FF; Miscellaneous Mathematical Symbols-B
#define TB_UNICODE_BLOCK_MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B @"TB_UNICODE_BLOCK_MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B"

//2A00..2AFF; Supplemental Mathematical Operators
#define TB_UNICODE_BLOCK_SUPPLEMENTAL_MATHEMATICAL_OPERATORS @"TB_UNICODE_BLOCK_SUPPLEMENTAL_MATHEMATICAL_OPERATORS"

//2B00..2BFF; Miscellaneous Symbols and Arrows
#define TB_UNICODE_BLOCK_MISCELLANEOUS_SYMBOLS_AND_ARROWS @"TB_UNICODE_BLOCK_MISCELLANEOUS_SYMBOLS_AND_ARROWS"

//2C00..2C5F; Glagolitic
#define TB_UNICODE_BLOCK_GLAGOLITIC @"TB_UNICODE_BLOCK_GLAGOLITIC"

//2C60..2C7F; Latin Extended-C
#define TB_UNICODE_BLOCK_LATIN_EXTENDED_C @"TB_UNICODE_BLOCK_LATIN_EXTENDED_C"

//2C80..2CFF; Coptic
#define TB_UNICODE_BLOCK_COPTIC @"TB_UNICODE_BLOCK_COPTIC"

//2D00..2D2F; Georgian Supplement
#define TB_UNICODE_BLOCK_GEORGIAN_SUPPLEMENT @"TB_UNICODE_BLOCK_GEORGIAN_SUPPLEMENT"

//2D30..2D7F; Tifinagh
#define TB_UNICODE_BLOCK_TIFINAGH @"TB_UNICODE_BLOCK_TIFINAGH"

//2D80..2DDF; Ethiopic Extended
#define TB_UNICODE_BLOCK_ETHIOPIC_EXTENDED @"TB_UNICODE_BLOCK_ETHIOPIC_EXTENDED"

//2DE0..2DFF; Cyrillic Extended-A
#define TB_UNICODE_BLOCK_CYRILLIC_EXTENDED_A @"TB_UNICODE_BLOCK_CYRILLIC_EXTENDED_A"

//2E00..2E7F; Supplemental Punctuation
#define TB_UNICODE_BLOCK_SUPPLEMENTAL_PUNCTUATION @"TB_UNICODE_BLOCK_SUPPLEMENTAL_PUNCTUATION"

//2E80..2EFF; CJK Radicals Supplement
#define TB_UNICODE_BLOCK_CJK_RADICALS_SUPPLEMENT @"TB_UNICODE_BLOCK_CJK_RADICALS_SUPPLEMENT"

//2F00..2FDF; Kangxi Radicals
#define TB_UNICODE_BLOCK_KANGXI_RADICALS @"TB_UNICODE_BLOCK_KANGXI_RADICALS"

//2FF0..2FFF; Ideographic Description Characters
#define TB_UNICODE_BLOCK_IDEOGRAPHIC_DESCRIPTION_CHARACTERS @"TB_UNICODE_BLOCK_IDEOGRAPHIC_DESCRIPTION_CHARACTERS"

//3000..303F; CJK Symbols and Punctuation
#define TB_UNICODE_BLOCK_CJK_SYMBOLS_AND_PUNCTUATION @"TB_UNICODE_BLOCK_CJK_SYMBOLS_AND_PUNCTUATION"

//3040..309F; Hiragana
#define TB_UNICODE_BLOCK_HIRAGANA @"TB_UNICODE_BLOCK_HIRAGANA"

//30A0..30FF; Katakana
#define TB_UNICODE_BLOCK_KATAKANA @"TB_UNICODE_BLOCK_KATAKANA"

//3100..312F; Bopomofo
#define TB_UNICODE_BLOCK_BOPOMOFO @"TB_UNICODE_BLOCK_BOPOMOFO"

//3130..318F; Hangul Compatibility Jamo
#define TB_UNICODE_BLOCK_HANGUL_COMPATIBILITY_JAMO @"TB_UNICODE_BLOCK_HANGUL_COMPATIBILITY_JAMO"

//3190..319F; Kanbun
#define TB_UNICODE_BLOCK_KANBUN @"TB_UNICODE_BLOCK_KANBUN"

//31A0..31BF; Bopomofo Extended
#define TB_UNICODE_BLOCK_BOPOMOFO_EXTENDED @"TB_UNICODE_BLOCK_BOPOMOFO_EXTENDED"

//31C0..31EF; CJK Strokes
#define TB_UNICODE_BLOCK_CJK_STROKES @"TB_UNICODE_BLOCK_CJK_STROKES"

//31F0..31FF; Katakana Phonetic Extensions
#define TB_UNICODE_BLOCK_KATAKANA_PHONETIC_EXTENSIONS @"TB_UNICODE_BLOCK_KATAKANA_PHONETIC_EXTENSIONS"

//3200..32FF; Enclosed CJK Letters and Months
#define TB_UNICODE_BLOCK_ENCLOSED_CJK_LETTERS_AND_MONTHS @"TB_UNICODE_BLOCK_ENCLOSED_CJK_LETTERS_AND_MONTHS"

//3300..33FF; CJK Compatibility
#define TB_UNICODE_BLOCK_CJK_COMPATIBILITY @"TB_UNICODE_BLOCK_CJK_COMPATIBILITY"

//3400..4DBF; CJK Unified Ideographs Extension A
#define TB_UNICODE_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A @"TB_UNICODE_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A"

//4DC0..4DFF; Yijing Hexagram Symbols
#define TB_UNICODE_BLOCK_YIJING_HEXAGRAM_SYMBOLS @"TB_UNICODE_BLOCK_YIJING_HEXAGRAM_SYMBOLS"

//4E00..9FFF; CJK Unified Ideographs
#define TB_UNICODE_BLOCK_CJK_UNIFIED_IDEOGRAPHS @"TB_UNICODE_BLOCK_CJK_UNIFIED_IDEOGRAPHS"

//A000..A48F; Yi Syllables
#define TB_UNICODE_BLOCK_YI_SYLLABLES @"TB_UNICODE_BLOCK_YI_SYLLABLES"

//A490..A4CF; Yi Radicals
#define TB_UNICODE_BLOCK_YI_RADICALS @"TB_UNICODE_BLOCK_YI_RADICALS"

//A4D0..A4FF; Lisu
#define TB_UNICODE_BLOCK_LISU @"TB_UNICODE_BLOCK_LISU"

//A500..A63F; Vai
#define TB_UNICODE_BLOCK_VAI @"TB_UNICODE_BLOCK_VAI"

//A640..A69F; Cyrillic Extended-B
#define TB_UNICODE_BLOCK_CYRILLIC_EXTENDED_B @"TB_UNICODE_BLOCK_CYRILLIC_EXTENDED_B"

//A6A0..A6FF; Bamum
#define TB_UNICODE_BLOCK_BAMUM @"TB_UNICODE_BLOCK_BAMUM"

//A700..A71F; Modifier Tone Letters
#define TB_UNICODE_BLOCK_MODIFIER_TONE_LETTERS @"TB_UNICODE_BLOCK_MODIFIER_TONE_LETTERS"

//A720..A7FF; Latin Extended-D
#define TB_UNICODE_BLOCK_LATIN_EXTENDED_D @"TB_UNICODE_BLOCK_LATIN_EXTENDED_D"

//A800..A82F; Syloti Nagri
#define TB_UNICODE_BLOCK_SYLOTI_NAGRI @"TB_UNICODE_BLOCK_SYLOTI_NAGRI"

//A830..A83F; Common Indic Number Forms
#define TB_UNICODE_BLOCK_COMMON_INDIC_NUMBER_FORMS @"TB_UNICODE_BLOCK_COMMON_INDIC_NUMBER_FORMS"

//A840..A87F; Phags-pa
#define TB_UNICODE_BLOCK_PHAGS_PA @"TB_UNICODE_BLOCK_PHAGS_PA"

//A880..A8DF; Saurashtra
#define TB_UNICODE_BLOCK_SAURASHTRA @"TB_UNICODE_BLOCK_SAURASHTRA"

//A8E0..A8FF; Devanagari Extended
#define TB_UNICODE_BLOCK_DEVANAGARI_EXTENDED @"TB_UNICODE_BLOCK_DEVANAGARI_EXTENDED"

//A900..A92F; Kayah Li
#define TB_UNICODE_BLOCK_KAYAH_LI @"TB_UNICODE_BLOCK_KAYAH_LI"

//A930..A95F; Rejang
#define TB_UNICODE_BLOCK_REJANG @"TB_UNICODE_BLOCK_REJANG"

//A960..A97F; Hangul Jamo Extended-A
#define TB_UNICODE_BLOCK_HANGUL_JAMO_EXTENDED_A @"TB_UNICODE_BLOCK_HANGUL_JAMO_EXTENDED_A"

//A980..A9DF; Javanese
#define TB_UNICODE_BLOCK_JAVANESE @"TB_UNICODE_BLOCK_JAVANESE"

//AA00..AA5F; Cham
#define TB_UNICODE_BLOCK_CHAM @"TB_UNICODE_BLOCK_CHAM"

//AA60..AA7F; Myanmar Extended-A
#define TB_UNICODE_BLOCK_MYANMAR_EXTENDED_A @"TB_UNICODE_BLOCK_MYANMAR_EXTENDED_A"

//AA80..AADF; Tai Viet
#define TB_UNICODE_BLOCK_TAI_VIET @"TB_UNICODE_BLOCK_TAI_VIET"

//AAE0..AAFF; Meetei Mayek Extensions
#define TB_UNICODE_BLOCK_MEETEI_MAYEK_EXTENSIONS @"TB_UNICODE_BLOCK_MEETEI_MAYEK_EXTENSIONS"

//AB00..AB2F; Ethiopic Extended-A
#define TB_UNICODE_BLOCK_ETHIOPIC_EXTENDED_A @"TB_UNICODE_BLOCK_ETHIOPIC_EXTENDED_A"

//ABC0..ABFF; Meetei Mayek
#define TB_UNICODE_BLOCK_MEETEI_MAYEK @"TB_UNICODE_BLOCK_MEETEI_MAYEK"

//AC00..D7AF; Hangul Syllables
#define TB_UNICODE_BLOCK_HANGUL_SYLLABLES @"TB_UNICODE_BLOCK_HANGUL_SYLLABLES"

//D7B0..D7FF; Hangul Jamo Extended-B
#define TB_UNICODE_BLOCK_HANGUL_JAMO_EXTENDED_B @"TB_UNICODE_BLOCK_HANGUL_JAMO_EXTENDED_B"

//D800..DB7F; High Surrogates
#define TB_UNICODE_BLOCK_HIGH_SURROGATES @"TB_UNICODE_BLOCK_HIGH_SURROGATES"

//DB80..DBFF; High Private Use Surrogates
#define TB_UNICODE_BLOCK_HIGH_PRIVATE_USE_SURROGATES @"TB_UNICODE_BLOCK_HIGH_PRIVATE_USE_SURROGATES"

//DC00..DFFF; Low Surrogates
#define TB_UNICODE_BLOCK_LOW_SURROGATES @"TB_UNICODE_BLOCK_LOW_SURROGATES"

//E000..F8FF; Private Use Area
#define TB_UNICODE_BLOCK_PRIVATE_USE_AREA @"TB_UNICODE_BLOCK_PRIVATE_USE_AREA"

//F900..FAFF; CJK Compatibility Ideographs
#define TB_UNICODE_BLOCK_CJK_COMPATIBILITY_IDEOGRAPHS @"TB_UNICODE_BLOCK_CJK_COMPATIBILITY_IDEOGRAPHS"

//FB00..FB4F; Alphabetic Presentation Forms
#define TB_UNICODE_BLOCK_ALPHABETIC_PRESENTATION_FORMS @"TB_UNICODE_BLOCK_ALPHABETIC_PRESENTATION_FORMS"

//FB50..FDFF; Arabic Presentation Forms-A
#define TB_UNICODE_BLOCK_ARABIC_PRESENTATION_FORMS_A @"TB_UNICODE_BLOCK_ARABIC_PRESENTATION_FORMS_A"

//FE00..FE0F; Variation Selectors
#define TB_UNICODE_BLOCK_VARIATION_SELECTORS @"TB_UNICODE_BLOCK_VARIATION_SELECTORS"

//FE10..FE1F; Vertical Forms
#define TB_UNICODE_BLOCK_VERTICAL_FORMS @"TB_UNICODE_BLOCK_VERTICAL_FORMS"

//FE20..FE2F; Combining Half Marks
#define TB_UNICODE_BLOCK_COMBINING_HALF_MARKS @"TB_UNICODE_BLOCK_COMBINING_HALF_MARKS"

//FE30..FE4F; CJK Compatibility Forms
#define TB_UNICODE_BLOCK_CJK_COMPATIBILITY_FORMS @"TB_UNICODE_BLOCK_CJK_COMPATIBILITY_FORMS"

//FE50..FE6F; Small Form Variants
#define TB_UNICODE_BLOCK_SMALL_FORM_VARIANTS @"TB_UNICODE_BLOCK_SMALL_FORM_VARIANTS"

//FE70..FEFF; Arabic Presentation Forms-B
#define TB_UNICODE_BLOCK_ARABIC_PRESENTATION_FORMS_B @"TB_UNICODE_BLOCK_ARABIC_PRESENTATION_FORMS_B"

//FF00..FFEF; Halfwidth and Fullwidth Forms
#define TB_UNICODE_BLOCK_HALFWIDTH_AND_FULLWIDTH_FORMS @"TB_UNICODE_BLOCK_HALFWIDTH_AND_FULLWIDTH_FORMS"

//FFF0..FFFF; Specials
#define TB_UNICODE_BLOCK_SPECIALS @"TB_UNICODE_BLOCK_SPECIALS"



//10000..1007F; Linear B Syllabary
#define TB_UNICODE_BLOCK_LINEAR_B_SYLLABARY @"TB_UNICODE_BLOCK_LINEAR_B_SYLLABARY"

//10080..100FF; Linear B Ideograms
#define TB_UNICODE_BLOCK_LINEAR_B_IDEOGRAMS @"TB_UNICODE_BLOCK_LINEAR_B_IDEOGRAMS"

//10100..1013F; Aegean Numbers
#define TB_UNICODE_BLOCK_AEGEAN_NUMBERS @"TB_UNICODE_BLOCK_AEGEAN_NUMBERS"

//10140..1018F; Ancient Greek Numbers
#define TB_UNICODE_BLOCK_ANCIENT_GREEK_NUMBERS @"TB_UNICODE_BLOCK_ANCIENT_GREEK_NUMBERS"

//10190..101CF; Ancient Symbols
#define TB_UNICODE_BLOCK_ANCIENT_SYMBOLS @"TB_UNICODE_BLOCK_ANCIENT_SYMBOLS"

//101D0..101FF; Phaistos Disc
#define TB_UNICODE_BLOCK_PHAISTOS_DISC @"TB_UNICODE_BLOCK_PHAISTOS_DISC"

//10280..1029F; Lycian
#define TB_UNICODE_BLOCK_LYCIAN @"TB_UNICODE_BLOCK_LYCIAN"

//102A0..102DF; Carian
#define TB_UNICODE_BLOCK_CARIAN @"TB_UNICODE_BLOCK_CARIAN"

//10300..1032F; Old Italic
#define TB_UNICODE_BLOCK_OLD_ITALIC @"TB_UNICODE_BLOCK_OLD_ITALIC"

//10330..1034F; Gothic
#define TB_UNICODE_BLOCK_GOTHIC @"TB_UNICODE_BLOCK_GOTHIC"

//10380..1039F; Ugaritic
#define TB_UNICODE_BLOCK_UGARITIC @"TB_UNICODE_BLOCK_UGARITIC"

//103A0..103DF; Old Persian
#define TB_UNICODE_BLOCK_OLD_PERSIAN @"TB_UNICODE_BLOCK_OLD_PERSIAN"

//10400..1044F; Deseret
#define TB_UNICODE_BLOCK_DESERET @"TB_UNICODE_BLOCK_DESERET"

//10450..1047F; Shavian
#define TB_UNICODE_BLOCK_SHAVIAN @"TB_UNICODE_BLOCK_SHAVIAN"

//10480..104AF; Osmanya
#define TB_UNICODE_BLOCK_OSMANYA @"TB_UNICODE_BLOCK_OSMANYA"

//10800..1083F; Cypriot Syllabary
#define TB_UNICODE_BLOCK_CYPRIOT_SYLLABARY @"TB_UNICODE_BLOCK_CYPRIOT_SYLLABARY"

//10840..1085F; Imperial Aramaic
#define TB_UNICODE_BLOCK_IMPERIAL_ARAMAIC @"TB_UNICODE_BLOCK_IMPERIAL_ARAMAIC"

//10900..1091F; Phoenician
#define TB_UNICODE_BLOCK_PHOENICIAN @"TB_UNICODE_BLOCK_PHOENICIAN"

//10920..1093F; Lydian
#define TB_UNICODE_BLOCK_LYDIAN @"TB_UNICODE_BLOCK_LYDIAN"

//10980..1099F; Meroitic Hieroglyphs
#define TB_UNICODE_BLOCK_MEROITIC_HIEROGLYPHS @"TB_UNICODE_BLOCK_MEROITIC_HIEROGLYPHS"

//109A0..109FF; Meroitic Cursive
#define TB_UNICODE_BLOCK_MEROITIC_CURSIVE @"TB_UNICODE_BLOCK_MEROITIC_CURSIVE"

//10A00..10A5F; Kharoshthi
#define TB_UNICODE_BLOCK_KHAROSHTHI @"TB_UNICODE_BLOCK_KHAROSHTHI"

//10A60..10A7F; Old South Arabian
#define TB_UNICODE_BLOCK_OLD_SOUTH_ARABIAN @"TB_UNICODE_BLOCK_OLD_SOUTH_ARABIAN"

//10B00..10B3F; Avestan
#define TB_UNICODE_BLOCK_AVESTAN @"TB_UNICODE_BLOCK_AVESTAN"

//10B40..10B5F; Inscriptional Parthian
#define TB_UNICODE_BLOCK_INSCRIPTIONAL_PARTHIAN @"TB_UNICODE_BLOCK_INSCRIPTIONAL_PARTHIAN"

//10B60..10B7F; Inscriptional Pahlavi
#define TB_UNICODE_BLOCK_INSCRIPTIONAL_PAHLAVI @"TB_UNICODE_BLOCK_INSCRIPTIONAL_PAHLAVI"

//10C00..10C4F; Old Turkic
#define TB_UNICODE_BLOCK_OLD_TURKIC @"TB_UNICODE_BLOCK_OLD_TURKIC"

//10E60..10E7F; Rumi Numeral Symbols
#define TB_UNICODE_BLOCK_RUMI_NUMERAL_SYMBOLS @"TB_UNICODE_BLOCK_RUMI_NUMERAL_SYMBOLS"

//11000..1107F; Brahmi
#define TB_UNICODE_BLOCK_BRAHMI @"TB_UNICODE_BLOCK_BRAHMI"

//11080..110CF; Kaithi
#define TB_UNICODE_BLOCK_KAITHI @"TB_UNICODE_BLOCK_KAITHI"

//110D0..110FF; Sora Sompeng
#define TB_UNICODE_BLOCK_SORA_SOMPENG @"TB_UNICODE_BLOCK_SORA_SOMPENG"

//11100..1114F; Chakma
#define TB_UNICODE_BLOCK_CHAKMA @"TB_UNICODE_BLOCK_CHAKMA"

//11180..111DF; Sharada
#define TB_UNICODE_BLOCK_SHARADA @"TB_UNICODE_BLOCK_SHARADA"

//11680..116CF; Takri
#define TB_UNICODE_BLOCK_TAKRI @"TB_UNICODE_BLOCK_TAKRI"

//12000..123FF; Cuneiform
#define TB_UNICODE_BLOCK_CUNEIFORM @"TB_UNICODE_BLOCK_CUNEIFORM"

//12400..1247F; Cuneiform Numbers and Punctuation
#define TB_UNICODE_BLOCK_CUNEIFORM_NUMBERS_AND_PUNCTUATION @"TB_UNICODE_BLOCK_CUNEIFORM_NUMBERS_AND_PUNCTUATION"

//13000..1342F; Egyptian Hieroglyphs
#define TB_UNICODE_BLOCK_EGYPTIAN_HIEROGLYPHS @"TB_UNICODE_BLOCK_EGYPTIAN_HIEROGLYPHS"

//16800..16A3F; Bamum Supplement
#define TB_UNICODE_BLOCK_BAMUM_SUPPLEMENT @"TB_UNICODE_BLOCK_BAMUM_SUPPLEMENT"

//16F00..16F9F; Miao
#define TB_UNICODE_BLOCK_MIAO @"TB_UNICODE_BLOCK_MIAO"

//1B000..1B0FF; Kana Supplement
#define TB_UNICODE_BLOCK_KANA_SUPPLEMENT @"TB_UNICODE_BLOCK_KANA_SUPPLEMENT"

//1D000..1D0FF; Byzantine Musical Symbols
#define TB_UNICODE_BLOCK_BYZANTINE_MUSICAL_SYMBOLS @"TB_UNICODE_BLOCK_BYZANTINE_MUSICAL_SYMBOLS"

//1D100..1D1FF; Musical Symbols
#define TB_UNICODE_BLOCK_MUSICAL_SYMBOLS @"TB_UNICODE_BLOCK_MUSICAL_SYMBOLS"

//1D200..1D24F; Ancient Greek Musical Notation
#define TB_UNICODE_BLOCK_ANCIENT_GREEK_MUSICAL_NOTATION @"TB_UNICODE_BLOCK_ANCIENT_GREEK_MUSICAL_NOTATION"

//1D300..1D35F; Tai Xuan Jing Symbols
#define TB_UNICODE_BLOCK_TAI_XUAN_JING_SYMBOLS @"TB_UNICODE_BLOCK_TAI_XUAN_JING_SYMBOLS"

//1D360..1D37F; Counting Rod Numerals
#define TB_UNICODE_BLOCK_COUNTING_ROD_NUMERALS @"TB_UNICODE_BLOCK_COUNTING_ROD_NUMERALS"

//1D400..1D7FF; Mathematical Alphanumeric Symbols
#define TB_UNICODE_BLOCK_MATHEMATICAL_ALPHANUMERIC_SYMBOLS @"TB_UNICODE_BLOCK_MATHEMATICAL_ALPHANUMERIC_SYMBOLS"

//1EE00..1EEFF; Arabic Mathematical Alphabetic Symbols
#define TB_UNICODE_BLOCK_ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS @"TB_UNICODE_BLOCK_ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS"

//1F000..1F02F; Mahjong Tiles
#define TB_UNICODE_BLOCK_MAHJONG_TILES @"TB_UNICODE_BLOCK_MAHJONG_TILES"

//1F030..1F09F; Domino Tiles
#define TB_UNICODE_BLOCK_DOMINO_TILES @"TB_UNICODE_BLOCK_DOMINO_TILES"

//1F0A0..1F0FF; Playing Cards
#define TB_UNICODE_BLOCK_PLAYING_CARDS @"TB_UNICODE_BLOCK_PLAYING_CARDS"

//1F100..1F1FF; Enclosed Alphanumeric Supplement
#define TB_UNICODE_BLOCK_ENCLOSED_ALPHANUMERIC_SUPPLEMENT @"TB_UNICODE_BLOCK_ENCLOSED_ALPHANUMERIC_SUPPLEMENT"

//1F200..1F2FF; Enclosed Ideographic Supplement
#define TB_UNICODE_BLOCK_ENCLOSED_IDEOGRAPHIC_SUPPLEMENT @"TB_UNICODE_BLOCK_ENCLOSED_IDEOGRAPHIC_SUPPLEMENT"

//1F300..1F5FF; Miscellaneous Symbols And Pictographs
#define TB_UNICODE_BLOCK_MISCELLANEOUS_SYMBOLS_AND_PICTOGRAPHS @"TB_UNICODE_BLOCK_MISCELLANEOUS_SYMBOLS_AND_PICTOGRAPHS"

//1F600..1F64F; Emoticons
#define TB_UNICODE_BLOCK_EMOTICONS @"TB_UNICODE_BLOCK_EMOTICONS"

//1F680..1F6FF; Transport And Map Symbols
#define TB_UNICODE_BLOCK_TRANSPORT_AND_MAP_SYMBOLS @"TB_UNICODE_BLOCK_TRANSPORT_AND_MAP_SYMBOLS"

//1F700..1F77F; Alchemical Symbols
#define TB_UNICODE_BLOCK_ALCHEMICAL_SYMBOLS @"TB_UNICODE_BLOCK_ALCHEMICAL_SYMBOLS"



//20000..2A6DF; CJK Unified Ideographs Extension B
#define TB_UNICODE_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B @"TB_UNICODE_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B"

//2A700..2B73F; CJK Unified Ideographs Extension C
#define TB_UNICODE_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C @"TB_UNICODE_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C"

//2B740..2B81F; CJK Unified Ideographs Extension D
#define TB_UNICODE_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D @"TB_UNICODE_BLOCK_CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D"

//2F800..2FA1F; CJK Compatibility Ideographs Supplement
#define TB_UNICODE_BLOCK_CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT @"TB_UNICODE_BLOCK_CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT"



//E0000..E007F; Tags
#define TB_UNICODE_BLOCK_TAGS @"TB_UNICODE_BLOCK_TAGS"

//E0100..E01EF; Variation Selectors Supplement
#define TB_UNICODE_BLOCK_VARIATION_SELECTORS_SUPPLEMENT @"TB_UNICODE_BLOCK_VARIATION_SELECTORS_SUPPLEMENT"



@interface TBUnicodeBlock : NSObject {
}

@property (nonatomic, readonly) NSUInteger begin;

@property (nonatomic, readonly) NSUInteger end;

@property (nonatomic, copy, readonly) NSString *name;


+ (TBUnicodeBlock *)blockOfChar:(NSUInteger)c;
+ (TBUnicodeBlock *)blockForName:(NSString *)n;

+ (NSArray *)blocks;
+ (NSArray *)blockNames;
+ (NSUInteger)blockCount;

- (BOOL)containsChar:(NSUInteger)c;
- (NSUInteger)length;

@end

